### ISSUE TITLE
Does not install anymore

### ISSUE THREAD

**Issue by howardkent** [em92/pickup-rating#14]
The code needs a refresh to get it inline with newer OS versions, package changes & library updates

**Comment by howardkent** [comment]
Example from Feeder install on Debian  6.1.0-13-amd64 (other errors on QLLR/python install not shown):

npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Python executable "/home/debian/quakelive-local-ratings/.venv/bin/python" is v3.11.2, which is not supported by gyp.
npm ERR! gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
npm ERR! gyp ERR! stack     at PythonFinder.failPythonVersion (/home/debian/quakelive-local-ratings/feeder/node_modules/node-gyp/lib/configure.js:492:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/home/debian/quakelive-local-ratings/feeder/node_modules/node-gyp/lib/configure.js:474:14)
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:411:7)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)

**Comment by em92** [comment]
What is your debian version?

**Comment by howardkent** [comment]
Originally I tried on Ubuntu 22.04.3 LTS, then again on Debian GNU/Linux 12 (Linux version 6.1.0-13-amd64 (debian-kernel@lists.debian.org) (gcc-12 (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29))

**Comment by em92** [comment]
Please run "git pull" in feeder and qllr directories and try again.

As for now introduced following patches:
https://github.com/em92/qlstats-feeder-mini/commit/ce18cbc23222a09fd111325f1c87de00eabfbfb0
https://github.com/em92/qlstats-feeder-mini/commit/d0aaa4df4ca12ed77a4e6bfa3de0011a803725d7
https://github.com/em92/quakelive-local-ratings/commit/0a5f7dc8fe2bd923dc2e063fbabe3e07ed087249

**Comment by howardkent** [comment]
1. Using a .venv to avoid python conflicts/errors with OS.

2. When creating the qllr database, I had to add 'ALTER DATABASE qllr OWNER TO eugene;' as the current version of postgres is v15. (see https://stackoverflow.com/questions/74110708/postgres-15-permission-denied-for-schema-public)

3. 'sudo apt-get install libzmq3' isn't a valid package anymore: I think the instruction should be either 'sudo apt-get install libzmq3' or 'sudo apt-get install libzmq3-dev', depending on the linux distribution.

4. There are 9 vulnerabilities, 6 moderate and 3 high in the npm packages. I assume you are aware of these. I'm not clear whether to fix some of these with 'npm audit fix --force' or not. I have left that as is. I recognise that some may not have fixes available.

5. I think Uvicorn now defaults to port 7081 rather than 8000, so have amended cfg.json. xonstatSubmissionUrl value accordingly.

**Comment by em92** [comment]
Updated docs on 1, 2, 3.

Fixed code on 5.

Working on 4.

**Comment by em92** [comment]
Btw, I recently updated starlette dependency. Make sure to use new one. Details: https://github.com/em92/quakelive-local-ratings/commit/64071d51bcaf7481a40f13c7bd879d84cf279e9d

**Comment by em92** [comment]
Did some changes on 4. As for now it is safe to use.

**Comment by em92** [comment]
Noting that recently installation method has been changed and there is given instructions, how to hide feeder behind nginx with password protection.
